# Generated by Django 6.0.4 on 2026-04-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saju', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchetypeSaju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('primary_element', models.CharField(max_length=10, verbose_name='본질 오행')),
                ('strongest_element', models.CharField(max_length=10, verbose_name='가장 강한 오행')),
                ('version', models.CharField(default='A', max_length=10, verbose_name='버전 (A/B/C)')),
                ('personality_summary', models.CharField(max_length=255, verbose_name='성격 요약')),
                ('personality_keywords', models.JSONField(verbose_name='성격 키워드 목록')),
                ('vitality_analysis', models.TextField(verbose_name='활력 분석서')),
                ('social_analysis', models.TextField(verbose_name='사회성 분석서')),
                ('treat_luck', models.TextField(verbose_name='간식운')),
                ('care_tips', models.TextField(verbose_name='케어 팁')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('primary_element', 'strongest_element', 'version'), name='unique_archetype_saju')],
            },
        ),
        migrations.CreateModel(
            name='DailyElementLuck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('date', models.DateField(verbose_name='해당 날짜')),
                ('element', models.CharField(max_length=10, verbose_name='주인공 오행')),
                ('luck_score', models.IntegerField(verbose_name='운세 점수')),
                ('message', models.TextField(verbose_name='산책운 메시지')),
                ('lucky_color', models.CharField(max_length=30, verbose_name='행운의 색')),
                ('lucky_direction', models.CharField(max_length=30, verbose_name='행운의 방향')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'element'), name='unique_daily_element_luck')],
            },
        ),
    ]
