# Generated by Django 6.0.4 on 2026-04-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saju', '0003_remove_archetypesaju_unique_archetype_saju_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityArchetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('dog_element', models.CharField(max_length=10, verbose_name='강아지 본질 오행')),
                ('relationship_type', models.CharField(max_length=10, verbose_name='십성 유형 (강아지↔보호자)')),
                ('version', models.CharField(default='A', max_length=5, verbose_name='버전')),
                ('score', models.IntegerField(verbose_name='궁합 점수 (0~100)')),
                ('title', models.CharField(max_length=100, verbose_name='궁합 타이틀')),
                ('description', models.TextField(verbose_name='궁합 상세 설명')),
                ('advice', models.TextField(verbose_name='보호자를 위한 관계 어드바이스')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dog_element', 'relationship_type', 'version'), name='unique_compatibility_archetype')],
            },
        ),
    ]
