# Generated by Django 6.0.4 on 2026-04-21 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saju', '0006_remove_dailyluckarchetype_unique_daily_luck_archetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('attended_days', models.JSONField(default=list, verbose_name='출석 일자 목록')),
                ('streak_count', models.IntegerField(default=0, verbose_name='연속 출석 일수')),
                ('claimed_milestones', models.JSONField(default=list, verbose_name='수령 완료된 마일스톤')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='보호자')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'year', 'month'), name='unique_user_monthly_attendance')],
            },
        ),
    ]
