# Generated by Django 6.1.1 on 2026-10-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saju', '0007_attendance_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='is_leap_month',
            field=models.BooleanField(default=False, verbose_name='윤달 여부'),
        ),
        migrations.AddField(
            model_name='dog',
            name='share_token',
            field=models.CharField(blank=True, help_text='공유 링크로 열람 가능한 공개 카드 식별자 (생일 등 민감 정보는 노출하지 않음)', max_length=32, null=True, unique=True, verbose_name='공유 카드 토큰'),
        ),
    ]
