# Generated by Django 6.0.4 on 2026-04-16 23:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('social_id', models.CharField(max_length=255, unique=True, verbose_name='Toss 식별값')),
                ('nickname', models.CharField(max_length=50, verbose_name='닉네임')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=50, verbose_name='강아지 이름')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('birth_time', models.TimeField(blank=True, null=True, verbose_name='태어난 시간')),
                ('is_lunar', models.BooleanField(default=False, verbose_name='음력 여부')),
                ('gender', models.CharField(choices=[('MALE', '수컷'), ('FEMALE', '암컷'), ('NEUTERED', '중성화')], max_length=10, verbose_name='성별')),
                ('is_estimated_birth', models.BooleanField(default=False, verbose_name='생일 추정 여부(유기견 등)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to=settings.AUTH_USER_MODEL, verbose_name='보호자')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('personality_summary', models.CharField(max_length=255, verbose_name='성격 요약')),
                ('personality_keywords', models.JSONField(verbose_name='성격 키워드 목록')),
                ('vitality_analysis', models.TextField(verbose_name='활력 분석서')),
                ('social_analysis', models.TextField(verbose_name='사회성 분석서')),
                ('treat_luck', models.TextField(verbose_name='간식운')),
                ('care_tips', models.TextField(verbose_name='케어 팁')),
                ('dog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interpretation', to='saju.dog', verbose_name='강아지')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SajuBasics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('year_pillar', models.CharField(max_length=10, verbose_name='년주')),
                ('month_pillar', models.CharField(max_length=10, verbose_name='월주')),
                ('day_pillar', models.CharField(max_length=10, verbose_name='일주')),
                ('hour_pillar', models.CharField(blank=True, max_length=10, null=True, verbose_name='시주')),
                ('main_element', models.CharField(max_length=10, verbose_name='일간 오행')),
                ('element_distribution', models.JSONField(help_text='목/화/토/금/수 비중 저장', verbose_name='오행 비중')),
                ('dog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saju_basics', to='saju.dog', verbose_name='강아지')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyWalkingLuck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('date', models.DateField(verbose_name='해당 날짜')),
                ('luck_score', models.IntegerField(verbose_name='운세 점수')),
                ('message', models.TextField(verbose_name='산책운 메시지')),
                ('lucky_color', models.CharField(max_length=30, verbose_name='행운의 색')),
                ('lucky_direction', models.CharField(max_length=30, verbose_name='행운의 방향')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_walking_lucks', to='saju.dog', verbose_name='강아지')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dog', 'date'), name='unique_dog_daily_luck')],
            },
        ),
        migrations.CreateModel(
            name='Compatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('score', models.IntegerField(verbose_name='궁합 점수')),
                ('title', models.CharField(help_text='예: 환상의 콤비', max_length=100, verbose_name='궁합 타이틀')),
                ('description', models.TextField(verbose_name='궁합 상세 설명')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to=settings.AUTH_USER_MODEL, verbose_name='대상 보호자')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='saju.dog', verbose_name='강아지')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dog', 'user'), name='unique_dog_user_compatibility')],
            },
        ),
    ]
