# Generated by Django 6.0.4 on 2026-04-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saju', '0002_archetypesaju_dailyelementluck'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='archetypesaju',
            name='unique_archetype_saju',
        ),
        migrations.AddField(
            model_name='archetypesaju',
            name='relationship_type',
            field=models.CharField(default='鍮꾧쾪', help_text='비겁/인성/식상/재성/관성', max_length=10, verbose_name='십성 유형'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sajubasics',
            name='relationship_type',
            field=models.CharField(blank=True, help_text='비겁/인성/식상/재성/관성', max_length=10, null=True, verbose_name='십성 유형'),
        ),
        migrations.AddField(
            model_name='sajubasics',
            name='secondary_element',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='2위 오행'),
        ),
        migrations.AddConstraint(
            model_name='archetypesaju',
            constraint=models.UniqueConstraint(fields=('primary_element', 'relationship_type', 'version'), name='unique_archetype_saju'),
        ),
        migrations.RemoveField(
            model_name='archetypesaju',
            name='strongest_element',
        ),
    ]
