# Generated by Django 6.0.4 on 2026-04-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saju', '0004_compatibilityarchetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLuckArchetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('dog_element', models.CharField(max_length=10, verbose_name='강아지 본질 오행')),
                ('relationship_type', models.CharField(help_text='비겁/인성/식상/재성/관성', max_length=10, verbose_name='십성 관계')),
                ('message', models.TextField(verbose_name='산책운 메시지 템플릿')),
                ('lucky_color', models.CharField(max_length=30, verbose_name='행운의 색')),
                ('lucky_direction', models.CharField(max_length=30, verbose_name='행운의 방향')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dog_element', 'relationship_type'), name='unique_daily_luck_archetype')],
            },
        ),
    ]
