# Generated by Django 6.0.4 on 2026-04-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saju', '0005_dailyluckarchetype'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyluckarchetype',
            name='unique_daily_luck_archetype',
        ),
        migrations.AddField(
            model_name='dailyluckarchetype',
            name='version',
            field=models.CharField(default='A', max_length=5, verbose_name='버전 (A/B/C)'),
        ),
        migrations.AddConstraint(
            model_name='dailyluckarchetype',
            constraint=models.UniqueConstraint(fields=('dog_element', 'relationship_type', 'version'), name='unique_daily_luck_archetype'),
        ),
    ]
